### ISSUE TITLE
Remove media/ from the repo

### ISSUE THREAD

**Issue by jamstooks** [AASHE/business-member-directory#1]
Since that's really for uploaded content, it doesn't belong in the repo. You can ignore it with .gitignore, but better yet, take a look at my [recommendations in django-integration-settings](https://github.com/AASHE/django-integration-settings/tree/master/integration_settings/media#recommendations).

**Comment by baronvonvaderham** [comment]
Absolutely. I should have mentioned it in the readme as a warning, I did that on purpose because I needed that temp logo image until I could get the edit interface working so there was an image to display when demoing this for the rest of the team. It will be taken out in the end.
