### ISSUE TITLE
Delete Link Failure

### ISSUE THREAD

**Issue by jamstooks** [AASHE/business-member-directory#10]
You might be seeing the error, but this page gives me a 500:

http://business-member-directory.herokuapp.com/business-member-directory/Kimberly-Clark-Professional-GA/link-delete/2/

I did get that page to work earlier. The button wasn't styled.

**Comment by baronvonvaderham** [comment]
Hmm, that's a weird error I hadn't seen before. I'll have to do some digging.

**Comment by baronvonvaderham** [comment]
Found it. I added the breadcrumb but just c/ped from the other templates where I have the member loaded into the context data. This one page has no member loaded, but changing it to link.member.slug instead fixes it.
