### ISSUE TITLE
Suggestion: remove 'detail'

### ISSUE THREAD

**Issue by jamstooks** [AASHE/business-member-directory#11]
It feels like the "detail" is superfluous in this link:

http://business-member-directory.herokuapp.com/business-member-directory/Kimberly-Clark-Professional-GA/detail/

What about this?

http://business-member-directory.herokuapp.com/business-member-directory/Kimberly-Clark-Professional-GA/

**Comment by baronvonvaderham** [comment]
Makes sense, I'm not sure why I did it that way.....probably one of those really early things I never thought about again.
