### ISSUE TITLE
Style suggestions

### ISSUE THREAD

**Issue by jamstooks** [AASHE/business-member-directory#12]
On the list page, consider

- using a slightly larger font for the business name
- using a [.table-striped](http://getbootstrap.com/2.3.2/base-css.html#tables) table for the list to clearly separate each row

**Comment by baronvonvaderham** [comment]
I did it that way originally and everyone hated having a table. I guess we can ask at the meeting tomorrow.

**Comment by baronvonvaderham** [comment]
Went ahead and did it, I like it (I liked the original table design back at the beginning). We'll see how everyone else reacts, I can always undo it. Also increased name font size.
