### ISSUE TITLE
Something fishy with pagination

### ISSUE THREAD

**Issue by jamstooks** [AASHE/business-member-directory#14]
Some organizations seem to be showing up on multiple pages, for example AGreenOZZI. It's at the end of the [first page](http://business-member-directory.herokuapp.com/business-member-directory/?page=1), and at the end of the [second page](http://business-member-directory.herokuapp.com/business-member-directory/?page=2).

Maybe something to do with the queryset? Also, I'd recommend ordering alphabetically.

**Comment by baronvonvaderham** [comment]
Hmmm. I couldn't duplicate this issue, but I went ahead and added a secondary sort field in the view as that's a good idea. There doesn't appear to be any issue at this time after redeploying to heroku.
