### ISSUE TITLE
Integrate aashe-auth

### ISSUE THREAD

**Issue by jamstooks** [AASHE/business-member-directory#7]
Add a login/logout button to mirror the primary site.

**Comment by baronvonvaderham** [comment]
Aha! I knew I forgot something. aasshe-auth is in there as the authentication back-end, but I do need to add a login button to the template.....probably the aashestrap base template, actually, not sure why it isn't in there.

**Comment by baronvonvaderham** [comment]
Updated the handy "user-navigation" block in my base.html and added some url patterns. They don't really work at the moment until we set up proxying so the base of this is aashe.org instead of the heroku app url.
